name: Check Language Versions

on: [push]

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check Python version
        run: python3 --version
      
      - name: Check Node.js version
        run: node --version
      
      - name: Check Java version
        run: java -version
      
      - name: Check Ruby version
        run: ruby --version
      
      - name: Check PHP version
        run: php --version
      
      - name: Check Go version
        run: go version
